### ISSUE TITLE
Get up project

### ISSUE THREAD

**Issue by shubaivan** [matks/ApiCycle#8]
Could you please understand me how to run project in local, maybe something manual gide, because I try standard steps, like executing `composer install` in each place where found `composer.lock`. Then in 
execute in `/apps/movies-api-client$` command ` php app/console check-api-client` and got exception about connection to server 

```
 cURL error 7: Failed to connect to 127.0.0.1 port 8000: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)  

```
Could you please  some manual please

**Comment by matks** [comment]
Hello, indeed the documentation is quite light on the setup part
I'll try to update this project with better setup explanations this week 😉

**Comment by shubaivan** [comment]
oy, sorry, I found blog post, my bad, sorry

**Comment by shubaivan** [comment]
in `apps/movies-api/composer.json` you missing `symfony/console` bundle
and atm I don't understand what version needed, because many conflicts with different othrs bundles

**Comment by shubaivan** [comment]
![_050](https://user-images.githubusercontent.com/1485872/45089589-4f707600-b115-11e8-9a90-0f8dd1057dc7.png)
I understand, `console` in master branch have been in gitignore. I checkout to `enable-circleci-build-2` and now `make` leaves when runnig `Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap`

**Comment by shubaivan** [comment]
and one more question I did not understand how to open web api documentation  .. :(

**Comment by matks** [comment]
@shubaivan I merged https://github.com/matks/ApiCycle/pull/10 which enhances the README setup sections and fix a few bugs I have found.

It should be fine now :) can you try and tell me your feedback ?

**Comment by shubaivan** [comment]
after composer install and running `symfony-scripts`, `make` exited from directory after 
 that => `Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap`

another parts work good

**Comment by matks** [comment]
Did you pull the updated `master` branch ?
Can you show me your terminal output for `make build` ?

Here is mine, on a fresh clone of the project:
```
matks:~/www/perso/ApiCycle (master)$ cd apps/movies-api
matks:~/www/perso/ApiCycle/apps/movies-api (master)$ make build
dev
/Library/Developer/CommandLineTools/usr/bin/make composer_install
test -f "composer.phar" || curl -s https://getcomposer.org/installer | php;
All settings correct for using Composer
Downloading...

Composer (version 1.7.2) successfully installed to: /Users/matks/www/perso/ApiCycle/apps/movies-api/composer.phar
Use it: php composer.phar

php composer.phar self-update
You are already using composer version 1.7.2 (stable channel).
php composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Package operations: 72 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-mbstring (v1.6.0): Loading from cache
  - Installing twig/twig (v2.4.4): Loading from cache
  - Installing symfony/polyfill-util (v1.6.0): Loading from cache
  - Installing paragonie/random_compat (v2.0.11): Loading from cache
  - Installing symfony/polyfill-php70 (v1.6.0): Loading from cache
  - Installing symfony/polyfill-php56 (v1.6.0): Loading from cache
  - Installing symfony/symfony (v3.1.10): Loading from cache
  - Installing symfony/polyfill-intl-icu (v1.6.0): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - ............
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Creating the "app/config/parameters.yml" file
Some parameters are missing. Please provide them.
database_host (127.0.0.1):
database_port (null):
database_name (symfony): movies_api
database_user (root):
database_password (null): root
secret (ThisTokenIsNotSoSecretChangeIt):
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
php bin/console --ansi cache:clear --env=dev

 // Clearing the cache for the dev environment with debug true

 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.

```

**Comment by matks** [comment]
Closed since I got no news for a while
